name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check Formatting
      run: cargo fmt --all -- --check
  feature-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Install cargo-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack
    - name: Check Feature Matrix
      run: cargo hack check --all --all-targets --feature-powerset --release
  test:
    name: Test (rust-toolchain.toml)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Run Tests
      run: cargo test --all-features --workspace --exclude=metrics-observer --exclude=metrics-benchmark
  test-matrixed:
    name: Test ${{ matrix.rust_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ['stable', 'nightly']
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Install Rust ${{ matrix.rust_version }}
      run: rustup install ${{ matrix.rust_version }}
    - name: Run Tests
      run: cargo +${{ matrix.rust_version }} test --all-features --workspace --exclude=metrics-observer --exclude=metrics-benchmark
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Install Rust Nightly
      run: rustup default nightly
    - name: Check Docs
      run: cargo doc --all-features --workspace --exclude=metrics-benchmark --no-deps
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Install Rust Stable
      run: rustup default stable
    - name: Run Benchmarks
      run: cargo bench --all-features --workspace --exclude=metrics-observer --exclude=metrics-benchmark
  clippy:
    name: Clippy ${{ matrix.rust_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ['1.61.0', 'stable', 'nightly']
    steps:
    - uses: actions/checkout@v3
    - name: Install Protobuf Compiler
      run: sudo apt-get install protobuf-compiler
    - name: Install Rust ${{ matrix.rust_version }}
      run: rustup default ${{ matrix.rust_version }}
    - name: Run Clippy
      run: cargo clippy --all-features --workspace --exclude=metrics-benchmark
